# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: crud-fe
  labels:
    app: crud-fe
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: crud-fe
  type: ClusterIP
